# Generated by Django 5.0.6 on 2024-06-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'ordering': ('-created_at',)},
        ),
    ]
